Completed node-notes-cli.
Mitchelllund/mod2-0822-code-solutions pull request #22
Opened 2022-10-11 00:54 UTC by Mitchelllund

![node-notes-cli](https://user-images.githubusercontent.com/90532731/194974121-cf98c6d7-3b9f-47e4-87b6-7de37bc336f2.gif)

2022-10-11 01:03 UTC, TimelikeClosure requested changes

2022-10-11 01:03 UTC, TimelikeClosure commented on node-notes-cli/app.js
> +  }
The update operation should only be able to modify existing notes, not create new ones

2022-10-11 23:25 UTC, Mitchelllund commented
![node-notes-cli-update](https://user-images.githubusercontent.com/90532731/195216298-56732fa7-b87f-4fe0-9aef-a40328b6712e.gif)

2022-10-12 01:06 UTC, TimelikeClosure approved these changes

2022-10-14 01:20 UTC, merged